# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=20)),
                ('startTime', models.CharField(max_length=10)),
                ('endTime', models.CharField(max_length=10)),
                ('shiftLength', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=15)),
                ('cluster', models.CharField(max_length=15)),
                ('isAssigned', models.BooleanField(default=False)),
                ('tbaCount', models.CharField(blank=True, max_length=15)),
                ('DP', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ('cluster', 'route'),
            },
        ),
        migrations.CreateModel(
            name='Tba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tba', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route')),
            ],
        ),
    ]
