# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_auto_20180310_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tba',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
        ),
    ]
