# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DPID', models.CharField(default=False, max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('checkin', models.BooleanField(default=False)),
                ('isAssigned', models.BooleanField(default=False)),
                ('shiftLength', models.CharField(blank=True, max_length=20)),
                ('startTime', models.CharField(blank=True, max_length=10)),
                ('endTime', models.CharField(blank=True, max_length=10)),
                ('isNoShow', models.BooleanField(default=True)),
                ('checkout', models.BooleanField(default=False)),
                ('packageScan', models.CharField(blank=True, max_length=3)),
                ('routingTool', models.CharField(blank=True, max_length=3)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Block')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route')),
            ],
        ),
    ]
