# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20180307_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='shiftLength',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
