# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20180307_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='endTime',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='shiftLength',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='startTime',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
